pipeline:
  # restore node_modules from cache
  restore-cache:
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache/drone/bit.cc:/cache

  # build
  build:
    image: node:16
    commands:
      - yarn install
      - npm run build

  # write node_modules back to cache
  rebuild-cache:
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./node_modules
    volumes:
      - /tmp/cache/drone/bit.cc:/cache

  # deploy production env
  deploy_production:
    image: drillster/drone-rsync
    hosts: [ $HOST_IP ]
    user: root
    secrets: [ rsync_key, host_ip ]
    source: ./
    target: /data/code/bit.cc
    script:
      - source ~/.zshrc
      - cd /data/code/bit.cc
      - npm run reload_production
    when:
      branch: [main]

  # deploy_test_env
  deploy_test:
    image: drillster/drone-rsync
    hosts: [$HOST_IP]
    user: root
    secrets: [ rsync_key, host_ip ]
    source: ./
    target: /data/code/bit.cc_test1
    script:
      - source ~/.zshrc
      - cd /data/code/bit.cc_test1
      - npm run reload_test1
    when:
      branch: [test]
